import pytest

from csvpath.references.functions.well_known_files.readme_3 import Readme3
from csvpath.references.functions.function_3 import Function3
from csvpath.references.reference_3 import Reference3
from csvpath.references.reference_exceptions_3 import ReferenceException3


def test_metadata():
    f = Readme3()
    assert f.name == "readme"
    # VALUE, not POINTER -- :readme() never narrows/selects anything,
    # even bare, same reasoning as Manifest3/Definition3.
    assert f.ROLE == Function3.VALUE
    # RESULTS has no README.md concept -- only named-file/named-paths
    # homes have one generated by the system.
    assert f.DATATYPES == (Reference3.FILES, Reference3.CSVPATHS)


def test_no_arg_is_valid():
    Readme3().check_valid()  # should not raise


def test_arg_is_rejected():
    with pytest.raises(ReferenceException3):
        Readme3(arg="x").check_valid()
