from ...reference_3 import Reference3
from ..function_3 import Function3


class Readme3(Function3):
    #
    # resolves to the raw bytes of the enclosing named-file/named-paths
    # group's own generated README.md, mirroring Definition3/Manifest3's
    # bare-content shape exactly -- see compendium 6.12/6.19. Genuinely
    # optional (a reference to a non-existent README.md returns None on
    # resolve(), same treatment as definition.json), but for a different
    # reason: README.md files are generated by the system by default, so
    # absence would be unusual rather than the normal case definition.
    # json's optionality represents.
    #
    # FILES/CSVPATHS only -- no README.md concept for RESULTS (compendium
    # 6.12's own note: "only named-paths and named-files homes have
    # readme files that are generated by the system"). Only ever legal
    # bare, as name_one's ENTIRE content -- no literal path, no trailing
    # chain, no name_three ("you cannot combine a path with the :readme()
    # function in name_one" -- compendium 6.12) -- enforced by the
    # finder via the same ReferenceFinder3._is_bare_pointer_reference()
    # check :manifest()/:definition() already use, not a grammar-level
    # restriction.
    #
    NAME = "readme"
    SUMMARY = (
        "The raw bytes of the enclosing named-file or named-paths "
        "group's own generated README.md. None if it does not exist. "
        "Only legal bare, as name_one's entire content -- no path, no "
        "further narrowing."
    )
    ROLE = Function3.VALUE
    # metadata_kind() override -- a whole-resource read, not a
    # single field, see Function3.RESOLVES_AS's own docstring for
    # why this class needs one (added 2026-08-28, this function added
    # 2026-09-21 following the same convention).
    RESOLVES_AS = Reference3.METADATA_FILE
    DATATYPES = (Reference3.FILES, Reference3.CSVPATHS)
    ARG_TYPES = ()
    ARG_REQUIRED = False
    POSITIONS = {
        Reference3.FILES: (Reference3.NAME_ONE,),
        Reference3.CSVPATHS: (Reference3.NAME_ONE,),
    }
