from lark import Lark, Tree, UnexpectedInput


#
# references v3 are AI-facing query strings over CsvPath Framework's
# named-file, named-paths, and named-results storage. see:
#   creating references v3.txt (project root)
# for the full spec this grammar implements.
#
# a reference has the shape:
#   $root_major.datatype.name_one[.name_three]
# where name_one may itself carry a "#name_two" (an XLSX worksheet name,
# files datatype only).
#
# design notes worth keeping in mind when reading this grammar:
#
# - name_three's required-ness differs by datatype (required for files and
#   csvpaths; optional for results, where its absence means "all files
#   generated by that run"). rather than tripling the reference rule per
#   datatype, name_three is kept grammatically optional everywhere and its
#   required-ness is enforced later as a semantic check (in the
#   transformer/finder, not yet built) against the already-parsed
#   datatype. this keeps the grammar itself flat and is the main way v3
#   avoids the combinatorial rule explosion of the v1/v2 grammar
#   (reference_grammar.py's files_names alone has ~25 alternatives).
#
# - "*" and a bare ":all()" function are interchangeable at a path-segment
#   position (both mean "everything at this level"). the grammar treats
#   them as distinct tokens/productions; the equivalence is a semantic
#   reading, not a grammar-level rewrite.
#
# - name_one is: an optional "/"-joined path (segments are a literal name,
#   "*", or a single function occupying the whole segment), optionally
#   followed by a "#name_two" worksheet marker, optionally followed by a
#   function chain (functions ANDed together with no separator between
#   them) -- or, when there's no literal/wildcard path at all, just a bare
#   function chain (e.g. ":all()", ":before(:yesterday()):index(3)").
#
# - name_three is: an optional single body (a literal name or "*", no path
#   building -- "name_three cannot have free-standing forward slashes" per
#   spec), optionally followed by a function chain -- or just a bare
#   function chain.
#
# - function arguments accept a quoted string, a signed int, an "@name"
#   runtime-bound variable, a nested function call, a slash-delimited
#   regex literal (REGEX, e.g. :name(/^(?:Mon|Tue)day$/) -- mirrors the
#   REGEX/REGEX_INNER convention already used by the match-language
#   grammar in csvpath/matching/lark_parser.py), or a bare/unquoted
#   token (BARE_ARG) for the simple spec'd case of an unquoted regex
#   with no parens or quotes, e.g. :name(^[^M].*). BARE_ARG excludes
#   "(", ")", '"', and "/" -- the parens and quote so it can't swallow
#   a function's closing ")" or be confused with STRING, and "/" so it
#   can never collide with REGEX's leading delimiter. A bare argument
#   that needs real regex grouping (capture or non-capturing) has no
#   way to represent it, since "(" "and ")" are excluded outright and
#   are themselves the group syntax -- that's what REGEX is for.
#
REFERENCE_GRAMMAR_3 = r"""
    ?start: reference

    reference: "$" root_major "." datatype "." name_one ("." name_three)?

    root_major: STAR
              | IDENTIFIER

    datatype: FILES
            | CSVPATHS
            | RESULTS

    FILES: "files"
    CSVPATHS: "csvpaths"
    RESULTS: "results"

    //========================================
    // name_one: optional "/"-joined path, optional #worksheet (files
    // only, but not restricted here -- see module docstring), optional
    // trailing function chain. or, with no path at all, a bare function
    // chain.

    name_one: path_prefix ("#" name_two)? func_chain?
            | func_chain

    path_prefix: segment ("/" segment)*
    segment: STAR
           | PATH_SEGMENT
           | function

    name_two: IDENTIFIER

    //========================================
    // name_three: optional single body (no path building), optional
    // trailing function chain. or a bare function chain.

    name_three: (PATH_SEGMENT | STAR) func_chain?
              | func_chain

    //========================================
    // functions: colon-prefixed, 0 or 1 arg, chainable with no separator
    // between them (functions are ANDed together per spec).

    func_chain: function+
    function: ":" FNAME "(" arg? ")"

    arg: STRING
       | SIGNED_INT
       | AT_VAR
       | function
       | REGEX
       | BARE_ARG

    //========================================
    // terminals

    STAR: "*"
    AT_VAR: "@" IDENTIFIER
    FNAME: /[a-zA-Z_][a-zA-Z0-9_]*/
    IDENTIFIER: /[a-zA-Z_][a-zA-Z0-9_\-]*/
    PATH_SEGMENT: /[a-zA-Z0-9_\-]+/
    STRING: /"(?:[^"\\]|\\.)*"/
    SIGNED_INT: /-?\d+/
    //
    // slash-delimited regex literal, for arguments that need real regex
    // grouping (capture or non-capturing) or a literal quote character --
    // neither of which BARE_ARG below can represent. matches the
    // REGEX/REGEX_INNER convention in csvpath/matching/lark_parser.py.
    //
    REGEX: "/" REGEX_INNER "/"
    REGEX_INNER: /([^\/\\]|\\.)*/
    //
    // bare/unquoted function argument. used for the simple spec'd case
    // of an unquoted regex with no parens or quotes (:name(^[^M].*)).
    // excludes "(", ")", and the quote char so it can never swallow a
    // function's closing paren or be confused with STRING, and "/" so
    // it can never collide with REGEX's leading delimiter.
    //
    BARE_ARG: /[^()"\/]+/

    %import common.WS
    %ignore WS
"""


class QueryParser3:
    #
    # syntax-only parser for references v3. builds and validates the parse
    # tree; does not (yet) transform it into a ReferenceParser3 object
    # graph or enforce datatype-specific semantic rules (e.g. name_three
    # being required for files/csvpaths) -- that is deferred to the
    # transformer, not yet built. see module docstring.
    #
    def __init__(self) -> None:
        self.parser = Lark(REFERENCE_GRAMMAR_3, parser="earley")

    def parse(self, query: str) -> Tree:
        if not query:
            raise ValueError("Query cannot be None or empty")
        return self.parser.parse(query)

    def validate_query(self, query: str) -> bool:
        try:
            self.parse(query)
            return True
        except UnexpectedInput:
            return False
